### ISSUE TITLE
1.7rc1 installation issue on Ubuntu 22.10

### ISSUE THREAD

**Issue by klacointe** [AZMCode/asdf-jq#15]
```zsh
~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
~ asdf plugin-add jq https://github.com/AZMCode/asdf-jq.git
~ asdf install jq 1.6                                 
~ jq --version
jq-1.6
~ asdf install jq 1.7rc1                              
curl: (3) URL using bad/illegal format or missing URL
~ asdf list jq
 *1.6
 ```

**Comment by mehalter** [comment]
I can confirm this issue continuing through the full 1.7 release

**Comment by mablanco** [comment]
I'd like to add more information about this issue as I've been suffering it recently. It happens in Linux based machines but it works in MacOS ARM64, though.

After further investigation, it seems that the plugin isn't able to correctly parse the information on the new supported architectures in `jq` 1.7 that it gets from the Github repository. These are the URLs passed to curl for downloading versions 1.6 and 1.7:

**1.6**
`curl -A curl/1.0.0 -H 'Accept: application/json' -fsS -L -o /home/user/.asdf/downloads/jq/1.6/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64`

**1.7**
`curl -A curl/1.0.0 -H 'Accept: application/json' -fsS -L -o /home/user/.asdf/downloads/jq/1.7/bin/jq 'https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64 https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-arm64 https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-mips64 https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-mips64el https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-mips64r6 https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-mips64r6el https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-ppc64el https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-riscv64 https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux64'`
