### ISSUE TITLE
jq 1.6 has disappeared

### ISSUE THREAD

**Issue by NikolayMetchev** [AZMCode/asdf-jq#5]
Not sure if there is a workaround that the plugin can do for this problem here:
https://github.com/stedolan/jq/issues/2430

**Comment by AZMCode** [comment]
As far as I understand it, I took so long to address this issue it fixed itself upstream, so that's cool, but I understand we may need to handle downloading from an alternate source were this to happen again. I may start work on that.
For now, closed.
