### ISSUE TITLE
jq repository has moved

### ISSUE THREAD

**Issue by tigerquoll** [AZMCode/asdf-jq#8]
curl -fsS https://api.github.com/repos/stedolan/jq/releases
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/5101141/releases",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}

**Comment by vespian** [comment]
+1

**Comment by vespian** [comment]
For anybody stumbling into it: gojq could be an alternative worth switching to:

https://github.com/itchyny/gojq#difference-to-jq
